SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Sembra esistere una relazione tra\n"
	.string "CENERIDE e il MONTE PIRA.\p"
	.string "Ho condotto delle ricerche insieme ad\n"
	.string "amici nel laboratorio dove lavoravo.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Mio fratello maggiore ha studiato\n"
	.string "biologia marina.$"

