WildPokemonCaveRoom2_MapScripts::
# 2 "data/maps/WildPokemonCaveRoom2/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, WildPokemonCaveRoom2_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE
	.byte 0

WildPokemonCaveRoom2_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE:
# 3 "data/maps/WildPokemonCaveRoom2/scripts.pory"
	map_script_2 VAR_TEMP_0, VAR_VALUE_GOT_KOED, Script_BidoofHeal_Underwater_GotKOedByWild
	.2byte 0

