#ifndef GUARD_CONFIG_CONSTANTS_FIELD_PIC_H
#define GUARD_CONFIG_CONSTANTS_FIELD_PIC_H

#define FIELD_PIC_BIDOOF_NORMAL 0
#define FIELD_PIC_BIDOOF_HAPPY  1
#define FIELD_PIC_BIDOOF_UNEASY 2
#define FIELD_PIC_BIDOOF_SAD    3
#define FIELD_PIC_BIDOOF_CRYING 4
#define FIELD_PIC_BIDOOF_SMIRKY 5
#define FIELD_PIC_BIDOOF_ASTONISHED 6
#define FIELD_PIC_BIDOOF_DIZZY 7
#define FIELD_PIC_BIDOOF_BLUSHED 8
#define FIELD_PIC_BIDOOF_HMM 9
#define FIELD_PIC_BIDOOF_SAD_UNEASY 10
#define FIELD_PIC_WINGULL 11
#define FIELD_PIC_HIKER 12
#define FIELD_PIC_SUICUNE 13
#define FIELD_PIC_ROTOM 14
#define FIELD_PIC_PHANPY_SAD 15
#define FIELD_PIC_PHANPY_SWEAT 16
#define FIELD_PIC_PHANPY_CONFUSED 17
#define FIELD_PIC_PHANPY_DETERMINED 18
#define FIELD_PIC_ABRA_ANGRY 19
#define FIELD_PIC_ABRA_CONCERNED 20
#define FIELD_PIC_ABRA_CRY 21
#define FIELD_PIC_ABRA_DETERMINED 22
#define FIELD_PIC_ABRA_HAPPY 23
#define FIELD_PIC_ABRA_JOY 24
#define FIELD_PIC_ABRA_SERIOUS 25
#define FIELD_PIC_ABRA_SURPRISED 26
#define FIELD_PIC_ABRA_SWEAT 27
#define FIELD_PIC_ABRA_THINKING 28
#define FIELD_PIC_SWABLU_ANGRY 29
#define FIELD_PIC_SWABLU_YELL 30
#define FIELD_PIC_FIDOUGH_SURPRISED 31
#define FIELD_PIC_APPLIN_DETERMINED 32
#define FIELD_PIC_SINISTEA_HAPPY 33
#define FIELD_PIC_VANILLITE_SIGH 34
#define FIELD_PIC_VANILLITE_ANGRY 35
#define FIELD_PIC_HAUNTER_INSPIRED 36
#define FIELD_PIC_HAUNTER_SIGH 37
#define FIELD_PIC_HAUNTER_YELL 38

#define FIELD_PIC_TATSUGIRI_SPECIAL 41
#define FIELD_PIC_FARFETCHD_DETERMINED 42
#define FIELD_PIC_SMOLIV_CRY 43
#define FIELD_PIC_NACLI_NORMAL 44

#define FIELD_PIC_TINKATON_DETERMINED 45
#define FIELD_PIC_TINKATON_INSPIRED 46
#define FIELD_PIC_TINKATON_ANGRY 47
#define FIELD_PIC_TINKATON_HAPPY 48
#define FIELD_PIC_TINKATON_SAD 49
#define FIELD_PIC_SCOLIPEDE_ANGRY 50
#define FIELD_PIC_SCOLIPEDE_WORRIED 51
#define FIELD_PIC_BLASTOISE_NORMAL 52
#define FIELD_PIC_BLASTOISE_ANGRY 53
#define FIELD_PIC_BLASTOISE_PAIN 54

#define FIELD_PIC_CRADILY_DARK 55
#define FIELD_PIC_CRADILY_DETERMINED 56

#define FIELD_PIC_PHOTO_PIECE_1 57
#define FIELD_PIC_PHOTO_PIECE_2 58
#define FIELD_PIC_PHOTO_PIECE_3 59
#define FIELD_PIC_PHOTO_PIECE_4 60
#define FIELD_PIC_PHOTO_PIECE_5 61
#define FIELD_PIC_PHOTO_WHOLE_A 62
#define FIELD_PIC_PHOTO_WHOLE_B 63

#define MSG_PORTRAIT_X 40
#define MSG_PORTRAIT_Y 96

#endif
