#ifndef GUARD_CONFIG_CONSTANTS_FIELD_PIC_H
#define GUARD_CONFIG_CONSTANTS_FIELD_PIC_H

#define FIELD_PIC_BIDOOF_NORMAL 0
#define FIELD_PIC_BIDOOF_HAPPY  1
#define FIELD_PIC_BIDOOF_UNEASY 2
#define FIELD_PIC_BIDOOF_SAD    3
#define FIELD_PIC_BIDOOF_CRYING 4
#define FIELD_PIC_BIDOOF_SMIRKY 5
#define FIELD_PIC_BIDOOF_ASTONISHED 6
#define FIELD_PIC_BIDOOF_DIZZY 7
#define FIELD_PIC_BIDOOF_BLUSHED 8
#define FIELD_PIC_BIDOOF_HMM 9
#define FIELD_PIC_BIDOOF_SAD_UNEASY 10
#define FIELD_PIC_WINGULL 11
#define FIELD_PIC_HIKER 12
#define FIELD_PIC_SUICUNE 13
#define FIELD_PIC_ROTOM 14

#define MSG_PORTRAIT_X 40
#define MSG_PORTRAIT_Y 96

#endif
