#ifndef GUARD_CONSTANTS_MANSION_FLOOR_GENERATION_H
#define GUARD_CONSTANTS_MANSION_FLOOR_GENERATION_H

enum ROOM_ENUM
{
    ROOM_NOTHING,
    ROOM_ENTRANCE,
    // 4Way enums must follow this order from 1 to last
    ROOM_4WAY_1,
    ROOM_4WAY_2,
    ROOM_4WAY_3,
    ROOM_4WAY_4,
    ROOM_HALLWAY_1,
    ROOM_HALLWAY_2,
    ROOM_TREASURE_UP,
    ROOM_TREASURE_DOWN,
    ROOM_TREASURE_LEFT,
    ROOM_TREASURE_RIGHT,
    ROOM_BOSS,
};

#endif
