MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "This disc is near a patch of wild seeds.\p"
	.string "In its reflection, you see yourself\n"
	.string "firing seeds at your enemies?\p"
	.string "Look closer?$"

MoveTutor_Text_SwaggerDeclined:
	.string "No need for seeds!$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Who wants to carry the seeds?$"

MoveTutor_Text_SwaggerTaught:
	.string "Pocket seeds!$"



MoveTutor_Text_RolloutTeach:
	.string "This disc is burned at the edges.\p"
	.string "In its reflection, you see yourself\n"
	.string "bite and cook food simultaneously?\p"
	.string "Look closer?$"

MoveTutor_Text_RolloutDeclined:
	.string "Berries are better raw!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Who's hungry?$"

MoveTutor_Text_RolloutTaught:
	.string "Yum.$"



MoveTutor_Text_FuryCutterTeach:
	.string "This disc looks like a shiny pillow.\p"
	.string "In its reflection, you see true beauty…\n"
	.string "a peaceful nap. You need this!\p"
	.string "Look closer?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Nah, there's too much to do.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Who's ready for a nap?!$"

MoveTutor_Text_FuryCutterTaught:
	.string "Yaaaaaaaawn.$"


MoveTutor_MimicTeach:
	.string "This disc looks pretty helpful.\p"
	.string "In its reflection, you see the\n"
	.string "true meaning of friendship?\p"
	.string "Look closer?$"

MoveTutor_MimicDeclined:
	.string "Nah, every 'mon for themselves!$"

MoveTutor_Text_MimicWhichMon:
	.string "Who's the better friend?$"

MoveTutor_Text_MimicTaught:
	.string "There's no I in team!$"



MoveTutor_Text_MetronomeTeach:
	.string "This disc looks annoying.\p"
	.string "In its reflection, you see many\n"
	.string "perfect sets and synergies ruined.\p"
	.string "Look closer?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Nah, let's see what they have!$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Who's more annoying?$"

MoveTutor_Text_MetronomeTaught:
	.string "If they wanted their item, they\n"
	.string "should have had Sticky Hold!$"




MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "I can teach your POKéMON how to\n"
	.string "SLEEP TALK instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with HIDDEN POWER, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
