SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "A seguito di un’eruzione, un vulcano\n"
	.string "sottomarino è emerso dalle profondità.\p"
	.string "Il cratere affiorato dal mare si\n"
	.string "è riempito di acqua piovana.\p"
	.string "Questa è l’origine di CENERIDE.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "La grotta che collega CENERIDE\n"
	.string "al mondo esterno…\p"
	.string "sembra che sia stata creata per\n"
	.string "custodire qualcosa.\p"
	.string "O forse mi sto inventando le cose?$"

