PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Viaggiare è magnifico!\p"
	.string "Quando ero giovane, ho navigato\n"
	.string "mari e scalato montagne!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sigh…\p"
	.string "Mi piacerebbe partire all’avventura\n"
	.string "con alcuni POKéMON…\p"
	.string "camminare sull’erba umida…\n"
	.string "scalare montagne impervie e rocciose…\p"
	.string "attraversare mari in burrasca…\n"
	.string "addentrarmi in grotte oscure…\p"
	.string "provare a volte un po’ di nostalgia…\p"
	.string "Viaggiare deve essere meraviglioso!$"

