AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring:
	.string " un posto bellissimo da esplorare!\n"
	.string "Ci si diverte un sacco!\p"
	.string "Ci potrei scommettere che a bordo\n"
	.string "ci sono dei tesori nascosti.$"

