FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "ttà…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Che cos’è quella cosa?\p"
	.string "… … … … … …\p"
	.string "Oh, si chiama POKéDEX?\n"
	.string "È stratosferico!$"

