SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Progettare una nave è più simile\n"
	.string "alla costruzione di un edificio che all’\l"
	.string "assemblaggio di un mezzo di trasporto.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "È incredibile che una nave fatta di\n"
	.string "metallo pesante possa galleggiare!\p"
	.string "Non sprofonda grazie al principio\n"
	.string "della galleggiabilità.$"

