SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "Ti mostrerò le tecniche sublimi che ho\n"
	.string "imparato dal CAPOPALESTRA RODOLFO!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Perdonami, RODOLFO…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Se rompi tutte le mattonelle del\n"
	.string "pavimento avrai una bella sorpresina…$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Hai fatto tanta strada inutilmente,\n"
	.string "RODOLFO non lo vedrai mai!\p"
	.string "Se perdi con me, non avrai chance!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "Sei forte! Il tuo faccino d’angelo\n"
	.string "mi ha ingannato!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Forse sei forte abbastanza da non\n"
	.string "andare KO con un sol colpo di RODOLFO.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "Mi è bastato vedere RODOLFO\n"
	.string "lottare…\p"
	.string "per convincermi a diventare\n"
	.string "un ALLENATORE.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Lotti con gran classe!\n"
	.string "Mi hai lasciato di stucco…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "La tua grazia nella lotta è favolosa.\p"
	.string "Oh… è stata proprio una fortuna\n"
	.string "entrare nel mondo dei POKéMON.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "Adesso ti faccio vedere io cosa vuol\n"
	.string "dire vedersela brutta in una lotta!$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh… sei un portento.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "Ho qualcosa di interessante\n"
	.string "da raccontarti.\p"
	.string "Da RODOLFO ci arrivi calpestando\n"
	.string "tutte le mattonelle solo una volta.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "La PALESTRA di CENERIDE…\p"
	.string "È la PALESTRA POKéMON di più alto\n"
	.string "livello nella regione di HOENN…$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "Il tuo livello è impressionante!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "Anche se ti trovi in una PALESTRA di\n"
	.string "alto livello, non adagiarti sugli allori.\l"
	.string "Continua a lottare per diventare più\l"
	.string "forte, senza contare il divertimento!$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "Alleno i miei POKéMON con RODOLFO.\p"
	.string "Non mi prendere sotto gamba!$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "Mi hai battuto…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Vedo che hai del potenziale!\n"
	.string "Perché non ti alleni qui con noi?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Un elegante volteggio su una\n"
	.string "distesa di ghiaccio…\p"
	.string "Sarebbe proprio una prestazione\n"
	.string "di gran classe per un ALLENATORE!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Tolgo il disturbo!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "Lo so che è scontato, ma la forza\n"
	.string "di un ALLENATORE non ha nulla\l"
	.string "a che vedere con l’età.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Quando vedrai i miei POKéMON, non avrai\n"
	.string "il tempo di dire “Oops!”.$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Oops!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "Vorrei potermi dimenticare delle lotte\n"
	.string "perse in un “Oops!”.$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Se vuoi posso mandare in campo\n"
	.string "POKéMON veramente rari.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Ehi! Li hai guardati bene i miei POKéMON?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "Sono venuta in questa PALESTRA\n"
	.string "perché RODOLFO mi aveva elogiato\l"
	.string "per i miei POKéMON.\p"
	.string "Se solo avessi incontrato RODOLFO\n"
	.string "anni fa quando ero più giovane…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Ahah… il tuo sguardo\n"
	.string "risoluto è così affascinante.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Oh, oh.\n"
	.string "Ti avevo preso sotto gamba.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "Non riuscirai a mettere le mani su\n"
	.string "RODOLFO. Mai! Ahah…$"

