LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "I misteri più grandi di questo pianeta\n"
	.string "giacciono sui fondali marini.\p"
	.string "L’ha detto qualcuno, ma non so chi…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "C’è una fossa sottomarina tra\n"
	.string "VERDEAZZUPOLI e CENERIDE.\p"
	.string "Almeno così mi è stato detto.$"

